# ----------------------------------------------------------------------------------------------------------------------
# ${project.artifactId}, version ${project.version} -  Configuration file.
# .
# You will find an explanation of all parameters here:
# https://github.com/arboriginal/${project.artifactId}/blob/master/src/main/resources/config.yml
# .
# Personal message: I'd love to have videos showing and explaining the plugin in use, but I'm not good at making vids...
# If you are able to make one, send me the link (preferred on Youtube) and I will include it (with credit and link)
# on the plugin page. English language is IMHO the most important, because it will be understandable by the most,
# but if you want to make a video in another language, I will include it too.
# .
# Remember to drink water, eat at least 5 fruits & vegetables a day and to be crazy all days, life is a big joke! ;)
# ----------------------------------------------------------------------------------------------------------------------

language: en # Choose lang file you want to use, actually, only en and fr exists, but you can set what you want: 
# If this lang file doesn't exist, a new one is created (copy of english, so you can edit it).

# If true, when you (re)load the plugin, it try to check if a new version is available
check_update: true

# You decide if your players can use both compass at the same time, or only one.
# In this case, you have to use « DISABLED » in one of the type's default option.
#
# This will NOT disallow the use of the other one. It simply act like a switch:
# If you activate ACTIONBAR, it will disable BOSSBAR.
# If you activate BOSSBAR, it will disable ACTIONBAR.
#
# If you want to restrict the use to a single type of compass, you can do it with permissions.
single_compass_mode: false

interface:
  give_book_everytime: false # If true, do not try to open a "virtual" book, give it instead.
  give_book_on_fail: true # If true, if the book interface cannot be auto opened, give the book to the player
  give_book_cooldown: 3600 # Time in seconds before a new book can be given to a player (if failed to open and give_book_on_fail=true)z

# Commands which can add an item to a player inventory, when used a check is done in case of a player now have required items.
commands_trigger_refresh:
- give

# If this list is not empty, all lores listed make items having ont of them be ignored by compass item requirements
ignored_lores: [] # « [] » represents an empty list, see below for an example of a filled list
# ignored_lores: []
# - This is not a compass item!
# - YOU SHALL NOT PASS!!!
# - A lore with §eyellow part.

# In compass strings, you can use colors with « § » followed with a number / letter:
# from 0 (black) to r (reset). See this link: https://wiki.ess3.net/mc/ (and don't forget to adjust the symbol).

compass:
  ACTIONBAR:
    default: # Applyed to players who have not yet chosen their options.
      mode: MODE360
      # Available values:
      # - MODE180         The compass will show cardinals / trackers in front of the player (180°)
      # - MODE360         The compass will show all cardinals / trackers (360°)
      option: VEHICLE
      # Available values:
      # - ALWAYS          The compass will always be visible
      # - ELYTRA          The compass will be visible only when gliding with elytras
      # - VEHICLE         The compass will be visible only when in a vehicle (horse, boat, ...)
      # - ELYTRA_VEHICLE  Combination of ELYTRA and VEHICLE
      # - DISABLED        The compass will not be displayed

    require: # List of items can be empty « [] » or contains several items, in this case one of them is needed.
      items: # See this list for available item names: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
        OFF_HAND: []  # Off hand is where you will wear your shield, ...
        MAIN_HAND:    # AIR works like an empty list, here only to give you an example.
        - AIR         # (If one item is AIR, the full list will be ignored)
        HOTBAR: []    # The 9 slots you see under your life and food levels
        INVENTORY: [] # All items you have in the inventory (4 x 9 slots, not in hotbar)
      # About required items:
      # - If AIR is in the list, it will be considered as an empty list
      # - If you fill several lists, the first one is checked, then the second if the player has not the first requirement, etc
      #
      # So, if you have:
      #
      # items:              It will result in:
      #   OFF_HAND: []      1. Look for a dirt in main hand, found => display the compass, stop to search (*)
      #   MAIN_HAND:        2. Look for a stick in main hand, found => display the compass, stop to search (*)
      #   - DIRT            3. Look for a diamond in the inventory, found => display the compass, stop to search (*)
      #   - STICK           4. Compass not displayed
      #   HOTBAR:                                      /!\ As hotbar contains air, the plugin will not search in it.
      #   - DIAMOND
      #   - AIR             (*) Consume it if require_settings.consume is true
      #   INVENTORY:
      #   - DIAMOND

      # The 2 next parameters are ignored if no item (nor AIR) is present in « items »
      consume: false  # if true, the required item will be consumed (the first one non AIR in the list, then the second if not found, etc)
      duration: 300   # When consumed, this is the cooldown (in seconds) not to re-consume another item.
                      # Players item are only consumed when the player moves, and the cooldown is not effective.
                      # So, for bossbar compass, it stays visible even if the player has consumed all necessary items he have until he move.
    MODE180:
      before: "§8--== [ "                         # Compass: <before> <sep> W <sep> N <sep> E <sep> S <sep> <after>
      separator_value: " ◣ ◛ ◈ ◛ ◢ ☗ ◣ ◛ ◈ ◛ ◢ "  # The separator (<sep>) can work with odd and even number of chars...
      separator_color: "§7"                       # Color of separators
      inactive_color: "§1"                        # Color of cardinals you're not facing
      active_color: "§6§l"                        # Color of the cardinal you"re facing
      north_color: "§4"                           # Color of the North (because it's always different on compasses...
      active_north_color: "§4§l"                  # Color of the Nothe if you are facing it.
      after: " §8] ==--"
      cardinals: # Those four cardinal points should have the same length for a better precision. If not, they will be filled with "filling_char".
        north: "North"
        east: "East "
        west: "West "
        south: "South"
        filling_char: " " # If they don't have the same length, this character will be used to fill the short ones. Put an empty string to disable.

    MODE360:                                      # See MODE180 for details, it works in the same way
      before: "§8--== [ "
      separator_value: " ■ ■ ☗ ■ ■ "
      separator_color: "§7"
      inactive_color: "§1"
      active_color: "§6§l"
      north_color: "§4"
      active_north_color: "§4§l"
      after: " §8] ==--"
      cardinals:
        north: "North"
        east: "East "
        west: "West "
        south: "South"
        filling_char: " "

    # Specific to actionbar...
    maintain_when_not_moving: false # If true, it will keep the actionbar compass when the player stop moving.
    maintain_delay: 40 # Server ticks value, after this, the compass datas are re-send to the actionbar.

  BOSSBAR:
    default:
      mode: MODE180
      option: ELYTRA

    require:
      items:
        OFF_HAND: []
        MAIN_HAND: []
        HOTBAR: []
        INVENTORY: []
      consume: false
      duration: 300

    MODE180:
      before: "§8[ "
      separator_value: "  ◇  ▴  ▲  ▴  ◇  "
      separator_color: "§7"
      inactive_color: "§3"
      active_color: "§e§l"
      north_color: "§6"
      active_north_color: "§6§l"
      after: " §8]"

      cardinals:
        north: "N"
        east: "E"
        west: "W"
        south: "S"
        filling_char: " "

    MODE360:
      before: "§8[ "
      separator_value: " ▴  ▲  ▴ "
      separator_color: "§7"
      inactive_color: "§3"
      active_color: "§e§l"
      north_color: "§6"
      active_north_color: "§6§l"
      after: " §8]"

      cardinals:
        north: "N"
        east: "E"
        west: "W"
        south: "S"
        filling_char: " "

    # Specific to bossbar...    /!\ it could take a few more than given seconds if your server is lagging (20 ticks = 1 second if no lags)
    disappear_when_not_moving: false # If true, it will hide the bossbar compass when the player stop moving after "disappear_delay" delay.
    disappear_delay: 50 # Server ticks value, 50 corresponds about to the same as actionbar delay (20 ticks = 1 second when no lags).
    warnPlayerNoMoreFuel: 3 # (in seconds.) When the player has no more the required items, time the warn message will stay visible

    attributes:
      color: GREEN  # available values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html  (or error invalid_bossbar_color)
      style: SOLID  # available values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html  (or error invalid_bossbar_style)
      progress: 0.0 # Value between 0 and 1 for the bossbar progress level.

      # You can use the elytra durability has progress length...
      elytra_durability:
        wearing: true # /!\ Will not force the display, only consider durability in bossbar progress, so you need ALWAYS (for example).
        gliding: true # Only applied when gliding with elytra, display the durability in bossbar progress length.
        levels:       # Use a different color for those given levels of durability (percentage)
          50: YELLOW
          20: RED

 # Order in which trackers will be displayed (if they are installed and activated)
trackers_priorities:
  - COORDS
  - PLAYER
  - POSITION
  - DEATH_POSITION
  # When a new tracker is added, a new entrie is put here. You can prepare this list before if you want:
  # trackerIDs here which correspond to nothing will be simply ignored.

# Advanced... Delays / cache durations (FYI: 20 ticks = 1 second if your server doesn't lag)
delays:
  update_version_cache: 60 # (minute) Duration of cache of online version found (should stay large or you will reach rate limit from Github)
  update_compass: 100    # (millisec) Compass datas refresh on player move, put 0 if you have predator's eyes
  trackers_list: 2000    # (millisec) Active trackers list (by player) cache 
  elytra_durability: 5   # (seconds)  Elytra durability calculation (if used in bossbar progress).
  fix_uuid: 50           # (ticks)    Time (after login) before to fix UUID which can happens, especialy in offline mode.
  option_take_effect: 20 # (ticks)    Time to wait before a new open takes effect in the currently active player compasses.
  refresh_status: 20     # (ticks)    Refresh compass status after specific actions (enter vehicle, using elytra, ...).
  pickup_refresh: 50     # (ticks)    Refresh compass status after player has pickup some items.
  target_cancel: 2       # (ticks)    Time after target creation input has been sent to perform the action
  # If compasses not appearing after (re)login, try a higher value. You can verify it's related by using /scompass-reload.
  # If after running this command, the compasses re-appear, the cause is a wrong player UUID discovery.

# Advanced... When showing a time (for example cooldown delays left), seconds are hidden if time is more than this value...
min_time_to_display_seconds: 180 # In seconds. Seconds will always be displayed under 60s, regardless this value.
